definitions:
  codes.ResCode:
    enum:
    - 1000
    - 1001
    - 1002
    - 1003
    - 1004
    - 1005
    - 1006
    - 1007
    - 1008
    - 1009
    - 1010
    - 1011
    - 1012
    - 1013
    - 1014
    - 1015
    - 1016
    - 1017
    - 1018
    - 1019
    - 1020
    - 1021
    - 1022
    - 1023
    - 1024
    - 1025
    - 1026
    - 1027
    type: integer
    x-enum-comments:
      BindDataError: 绑定数据错误
      CheckUserExistsError: 检查用户是否存在错误
      CodeSuccess: 成功
      CreateDirError: 创建文件夹错误
      CreateHouseError: 创建房屋错误
      CreateHouseImageError: 创建房屋图片错误
      GenerateJWTTokenError: 无法生成jwt token
      GetDBError: 数据库错误
      GetHouseInfoError: 获取某一个房屋信息错误
      GetHouseListError: 获取房屋列表错误
      GetUserFavouritesError: 获取用户收藏错误
      GetUserIDError: 获取用户ID错误
      GetUserProfileError: 获取用户信息错误
      HouseIDInvalid: 房屋ID无效
      LoginInvalidParam: 请求参数错误
      LoginInvalidPassword: 密码错误
      LoginServerBusy: 服务繁忙
      LoginUserNotExist: 用户不存在
      ModifyUserProfileError: 修改用户信息错误
      RegisterCreateUserError: 创建用户失败
      RegisterEmailExists: 邮箱已存在
      RegisterInvalidParam: 注册请求参数错误
      RegisterUsernameExists: 用户名已存在
      ReleaseBindDataError: 绑定数据错误
      ReserveError: 预约失败
      ReserveInvalidParam: 预约请求参数错误
      SaveFileError: 保存文件错误
      UserIDTypeError: 用户ID类型错误
    x-enum-varnames:
    - CodeSuccess
    - LoginInvalidParam
    - LoginUserNotExist
    - LoginInvalidPassword
    - LoginServerBusy
    - GetDBError
    - GenerateJWTTokenError
    - RegisterInvalidParam
    - CheckUserExistsError
    - RegisterUsernameExists
    - RegisterEmailExists
    - RegisterCreateUserError
    - ReserveInvalidParam
    - ReserveError
    - GetUserIDError
    - UserIDTypeError
    - GetHouseListError
    - GetHouseInfoError
    - HouseIDInvalid
    - ReleaseBindDataError
    - CreateDirError
    - SaveFileError
    - CreateHouseError
    - CreateHouseImageError
    - GetUserFavouritesError
    - GetUserProfileError
    - BindDataError
    - ModifyUserProfileError
  controller.ResponseData:
    properties:
      code:
        allOf:
        - $ref: '#/definitions/codes.ResCode'
        description: 自定义的返回码
      data:
        description: 返回的数据
      message:
        description: 返回的信息
    type: object
  model.HouseRequest:
    type: object
  model.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: Haonan_Fang@Outlook.com
    name: FHN
  description: 这是在线房屋交易平台的API文档, 用于提供房屋交易相关的接口, 包括用户注册、登录、房屋信息的增删改查等功能, 以及房屋图片的上传和获取等功能
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 在线房屋交易平台API文档
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: 显示首页
      produces:
      - application/json
      responses:
        "200":
          description: 首页
          schema:
            type: string
      summary: 首页
      tags:
      - 首页
  /appointment:
    post:
      consumes:
      - application/json
      description: 用户预约房屋
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 房屋ID
        in: body
        name: house_id
        required: true
        schema:
          type: integer
      - description: 预约时间
        in: body
        name: time
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 预约成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 预约房屋
      tags:
      - 预约
  /auth/login:
    get:
      consumes:
      - application/json
      description: 显示用户登录界面
      produces:
      - application/json
      responses:
        "200":
          description: 登录界面
          schema:
            type: string
      summary: 登录界面
      tags:
      - 登录
    post:
      consumes:
      - application/json
      description: 用户登录接口
      parameters:
      - in: query
        name: password
        type: string
      - in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 登录接口
      tags:
      - 登录
  /auth/register:
    get:
      consumes:
      - application/json
      description: 显示用户注册界面
      produces:
      - application/json
      responses:
        "200":
          description: 注册界面
          schema:
            type: string
      summary: 注册界面
      tags:
      - 注册
    post:
      consumes:
      - application/json
      description: 用户注册接口
      parameters:
      - in: query
        name: email
        type: string
      - in: query
        name: password
        type: string
      - in: query
        name: role
        type: string
      - in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 注册接口
      tags:
      - 注册
  /house:
    get:
      consumes:
      - application/json
      description: 获取所有房屋信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 获取所有房屋信息
      tags:
      - 房屋
  /house/{house_id}:
    get:
      consumes:
      - application/json
      description: 获取某个房屋的详细信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 房屋ID
        in: path
        name: house_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取失败
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 获取某个房屋的详细信息
      tags:
      - 房屋
  /houses/collect:
    post:
      consumes:
      - application/json
      description: 用户收藏房屋
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 房屋ID
        in: body
        name: house_id
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 收藏成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 收藏房屋
      tags:
      - 收藏
  /learn_more:
    get:
      consumes:
      - application/json
      description: 显示LearnMore页面
      produces:
      - application/json
      responses:
        "200":
          description: LearnMore页面
          schema:
            type: string
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: LearnMore
      tags:
      - LearnMore
  /profile/{user_id}:
    get:
      consumes:
      - application/json
      description: 获取个人信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 获取失败
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 获取个人信息
      tags:
      - 个人信息
  /profile/profile:
    put:
      consumes:
      - application/json
      description: 修改个人信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 用户信息
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/model.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 修改成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 修改失败
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 修改个人信息
      tags:
      - 个人信息
  /release:
    get:
      consumes:
      - application/json
      description: 获取发布房屋信息页面
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - text/html
      responses:
        "200":
          description: 发布房屋信息页面
          schema:
            type: string
      summary: 获取发布房屋信息页面
      tags:
      - 发布
    post:
      consumes:
      - application/json
      description: 发布房屋信息
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 发布房屋信息请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.HouseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 发布成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 发布失败
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 发布房屋信息
      tags:
      - 发布
  /user/{user_id}/collects:
    post:
      consumes:
      - application/json
      description: 获取用户收藏的房屋
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 用户ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            $ref: '#/definitions/controller.ResponseData'
        "400":
          description: 预约失败,具体原因查看json中的message字段和code字段
          schema:
            $ref: '#/definitions/controller.ResponseData'
      summary: 获取用户收藏的房屋
      tags:
      - 收藏
swagger: "2.0"
